# Generated by Django 6.0.5 on 2026-05-20 09:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_stocked', models.DecimalField(decimal_places=4, max_digits=14)),
                ('available_items', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('vat', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('total_amount_stocked', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('quantity_released', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('purchase_status', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store_management.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Store Transaction',
                'verbose_name_plural': 'Store Transactions',
                'ordering': ['date', 'product__name'],
            },
        ),
    ]
