# Generated by Django 6.0.5 on 2026-05-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetransaction',
            name='purchase_status',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('RELEAS', 'Release')], default='CASH', max_length=10),
        ),
    ]
