# Generated by Django 6.0.6 on 2026-06-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0002_alter_storetransaction_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetransaction',
            name='purchase_status',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('RELEASE', 'Release')], default='CASH', max_length=10),
        ),
    ]
