# Generated by Django 6.0.5 on 2026-05-20 05:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('truck_number_plate', models.CharField(max_length=50)),
                ('item_needed', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('vat_wth', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_at_net', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_status', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=10)),
                ('project', models.CharField(choices=[('CADDELL', 'Caddell'), ('ADHOC', 'Adhoc')], default='CADDELL', max_length=10)),
                ('cost_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fleet Maintenance Record',
                'verbose_name_plural': 'Fleet Maintenance Records',
                'ordering': ['-date', '-pk'],
            },
        ),
    ]
