# Generated by Django 6.0.6 on 2026-06-20 19:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('truck_number_plate', models.CharField(max_length=50)),
                ('item_released', models.CharField(max_length=255)),
                ('quantity_released', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('vat_wth', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_at_net', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_status', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=10)),
                ('project', models.CharField(choices=[('CADDELL', 'Caddell'), ('ADHOC', 'Adhoc')], default='CADDELL', max_length=10)),
                ('cost_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Spare / Maintenance Item Release',
                'verbose_name_plural': 'Spare / Maintenance Item Releases',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='fleetmaintenance',
            name='quantity_released',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='fleetmaintenance',
            name='quantity_stocked',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='fleetmaintenance',
            name='total_cost_remaining',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='fleetmaintenance',
            name='total_remaining_items',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
    ]
